### PR TITLE
Implement tag behaviour for extend custom tag easier

### PR DESCRIPTION
**Pull request by bluzky**
## In this PR
Propose a flexible way to define custom tag

1. Move expression for field and arguments to helper modules
2. Define a `behaviour` for custom tag
3. Add test for custom tag using module

To implement new custom tag you need to create new module that implement `CustomTag` behaviour:

```elixir
defmodule MyCustomTag do
  import NimbleParsec
  @behaviour Solid.Tag.CustomTag

  @impl true
  def spec() do
    space = Solid.Parser.Literal.whitespace(min: 0)

    ignore(string("{%"))
    |> ignore(space)
    |> ignore(string("my_tag"))
    |> ignore(space)
    |> ignore(string("%}"))
  end

  @impl true
  def render(_context, _binding, _options) do
    [text: "my first tag"]
  end
end
```

- `spec` define how to parse your tag
- `render` define how to render your tag

Then add custom tag to your parser

```elixir
defmodule MyParser do
  use Solid.Parser.Base, custom_tag: [{"my_tag", MyCustomTag}]
end
```

Then pass your tag to render function

```elixir
"{% my_tag %}"
|> Solid.parse!(parser: MyParser)
|> Solid.render(tags: %{"my_tag" => MyCustomTag})
```

### CODE REVIEW

**Comment by bluzky** [comment]
@edgurgel I add a behaviour for custom tag that I think it solves issues #43 and #48 and #80

**Comment by edgurgel** [comment]
Hey @bluzky , I really like the simplicity of this solution! Thank you so much for sending this PR.

I want to play with this branch so I might take a few days to get back to you.

**Comment by edgurgel** [comment]
This is great, @bluzky ❤️ 

This made me think a lot about how we can structure tags in general so that custom tags and "normal" tags can be structured the same way (for the most part). I might send a PR soon for you to review with some ideas.

I'm also tempted to simply deprecate (glad we are not 1.0 yet) passing just a  string for custom tags and relying on the tuple that is passed with the module name to call when rendering. So people don't need to define them twice (parser and `Solid.render` on options) 🤔

**Comment by bluzky** [comment]
Yeah, I think it would be a huge PR 😄

**Pull request merged**
