### PR TITLE
Implement strip_html filter

### PR DESCRIPTION
**Pull request by LostKobrakai**
This uses the exact same naive regex filters than the ruby version does.

### CODE REVIEW

**Comment by edgurgel** [comment]
I think that's good enough 👌

**Comment by edgurgel** [comment]
Hey sorry we  got some conflicts with all the merges!

**Comment by LostKobrakai** [comment]
Yeah, I reused an integration test number is seems. But for the filter.ex I'm not really sure why it's trying to merge those functions together? But I did rebase it on current master

**Comment by edgurgel** [comment]
Cheers! I will release a new version soon with all the new filters 🎉

**Pull request merged**
