### PR TITLE
Fixes import conflict issue in filter module

### PR DESCRIPTION
**Pull request by barkerja**

### CODE REVIEW

**Comment by edgurgel** [comment]
Hey thanks for the PR! I think we need to update the elixir and erlang requirements as Solid is still using a very old version 🤔 .

**Comment by barkerja** [comment]
Any issues with bumping up the version travis uses to `1.9.1` and `OTP 22`?

**Comment by edgurgel** [comment]
No issues at all! Let's do this! :D

**Comment by barkerja** [comment]
Pushed!

Also, I'll hopefully have a few more PRs right behind this one. Working on adding `for` tag support and also a way to make filters extensible.

**Comment by edgurgel** [comment]
That's amazing! 🎉

**Comment by barkerja** [comment]
Thanks! ✋

**Pull request merged**
