### PR TITLE
Update Elixir requirement to ~> 1.16

### PR DESCRIPTION
**Pull request by edgurgel**

### CODE REVIEW

**Comment by leandrocp** [comment]
Hi @edgurgel first of all, thanks for this lib! We've been using it in https://github.com/BeaconCMS/beacon and I just noticed a new release with these changes, which causes a bit of a conflict because Beacon requires `elixir: "~> 1.14"`. For reference Phoenix requires `1.11` and LV `1.13`.

I don't know the technical challenges of the parser so I might be something here, but I'm wondering if would be possible to revert this `1.16` requirement. Thanks!

**Comment by edgurgel** [comment]
Hi @leandrocp ! The elixir requirement is just a warning and it shouldn't stop you from using this library. Are you seeing any errors? Elixir 1.16 was released more than a year ago!

**Comment by leandrocp** [comment]
No errors, just a warning since it's a soft requirement at this point. Unless some code that depends on 1.16 is added then that would become a hard requirement. But that's okay we can keep using it and monitor new releases. Thanks for your time!

**Comment by leandrocp** [comment]
Yeah I get it. Maintenance requires time, no worries.

**Pull request merged**
