### PR TITLE
Support for custom filters

### LINKED ISSUE #11: Custom filters
https://shopify.github.io/liquid/basics/whitespace/

### PR DESCRIPTION
**Pull request by barkerja**
Closes #11

### CODE REVIEW

**Comment by barkerja** [comment]
@edgurgel I have not yet added any tests. Before I proceed any further, I wanted to run this idea by you to see if it's something you find valuable to the project.

The idea is an integrator would be able to find their own custom module of filters, telling Solid about it by `Application.put_env(:solid, :custom_filters, Custom.Filters`

Solid then checks if a custom filters module has been given. If yes, it first checks for the inclusion of the filter in the custom module, if the filter does not exist, it drops back to `Solid.Filter`, behaving as normal.

**Comment by edgurgel** [comment]
I like the idea! Let's do this! 🎉 

Thanks for the starting this :)

**Comment by barkerja** [comment]
@edgurgel I added a couple of basic tests for the new custom filter stuff.

**Comment by edgurgel** [comment]
That's awesome! I will release a new version soon 🎉

**Pull request merged**
