### PR TITLE
Add for tag support

### PR DESCRIPTION
**Pull request by barkerja**

### CODE REVIEW

**Comment by barkerja** [comment]
@edgurgel This PR adds basic support for the `for` tag. It does not yet have support for `break`. 

Can you think of any other tests, I should include to make sure all bases are covered? Thanks!

**Comment by edgurgel** [comment]
Hey thank you so much for the contribution! Would you mind adding a "integration" test case? It's basically a new directory here: https://github.com/edgurgel/solid/tree/master/test/cases

We put the `input.liquid` file with some args (if needed) inside `input.json` and we will run an integration test using the Ruby implementation to compare with ours. So a basic file with `for` usage would be awesome. 

What do you think?

**Comment by barkerja** [comment]
Absolutely! I’ll get a couple added soon.

**Comment by barkerja** [comment]
Test added!

**Comment by edgurgel** [comment]
Fantastic! 🎉 That's awesome!

**Pull request merged**
