### PR TITLE
added size attribute to binary values

### PR DESCRIPTION
**Pull request by SirFitz**
Added the ".size" attribute to binary values to get a string length.
eg: "{{post.title.size}}"

### CODE REVIEW

**Comment by edgurgel** [comment]
Hi @SirFitz ! Thanks for the PR!

Do you know if it should be `byte_size` or `String.length`?

```
iex(1)> byte_size("José")
5
iex(3)> String.length("José")
4
```

Also do you mind adding a new test inside `test/cases` ? It will test the case against the Liquid gem and our implementation.

**Comment by SirFitz** [comment]
Hi @edgurgel ,  

You're welcome and thanks for getting to the PR so quickly!

I just did some testing using the gem, it should be `String.length` instead of `byte_size`, thanks for that catch :) .

And sure, I will update the code and add the test cases.

**Comment by SirFitz** [comment]
Hi @edgurgel , 

I've made the update to from `byte_size` to `String.length` and added the new test case.

Let me know if all is well,
Thanks!

**Comment by edgurgel** [comment]
Thanks, @SirFitz ! Sorry for the delay! We should get a new version out soon with your contribution! 🎉

**Pull request merged**
