### PR TITLE
WIP 🚧: Support Whitespace Control For all Tags and Objects

### PR DESCRIPTION
**Pull request by Jcambass**
This patch is still very much WIP and a bit exploration but I opened it as a draft for visability and maybe gathering some needed inputs.

Also don't try to understand the random comments, that's just me trying to note my thoughts (which are very likely nonsense in many cases but I still want them to verify before just ignoring them :) ).

The major problems at the moment are:

- for loops
- capture tags
- raw tags

See: https://github.com/edgurgel/solid/issues/10

### CODE REVIEW

**Comment by edgurgel** [comment]
Thanks for starting this! I think it's the hardest part of rendering Liquid templates! Happy to help with anything I can

**Comment by Jcambass** [comment]
@edgurgel Thanks for offering your help! I will now first try to add test cases for every tag with (hopefully) all whitespace situations.
This makes some test case files such as the one for `if` tags quite big. I hope that's ok with you. I though about generating those cases but I think it's clear to understand the way it currently is:

https://github.com/edgurgel/solid/pull/67/files#diff-48525791295f171fbd7e19f374cd7df2f608e8696fd2c9294ad5df648b70f52eR1-R841

**Comment by Jcambass** [comment]
I currently hit a wall with this PR.
It's mostly related to the way Solid does parsing and rendering compared to the approach Liquid takes.
I will try to find some time to better explore and explain the differences between the two approaches but for now I just wanted to leave this comment for clarity on the current progress.

**Comment by edgurgel** [comment]
@Jcambass thanks for the heads-up. I will have a look at the PR this weekend and see if I can help somehow.

**Comment by Jcambass** [comment]
@edgurgel Sounds good. Be aware that it lacks some proper structure and direction.

I was switching the place where trimming happens multipel times up and down the layers but didn't find the right spot.

The liquid gem parses in a way where it operates more directly on the whole tag instead of first parsing it into clear datastructures like we do with nimbleparsec. It *feels* like there is some fancy term like small step semantics vs big steps semantics that might describe the difference but I'm not fully sure.

I have a hard time mapping the solution liquid takes to a solution that could work for solid while keeping the exact semantics without adding hardcased edge cases.

So before you get lost in this PR it might be better to have a look at liquids whitespace handling and think about how it conceptionally would transition to solid.

**Comment by edgurgel** [comment]
@Jcambass Here's an idea... what if we "annotate" the places where we must trim whitespaces and then on a second pass (after everything has been parsed and rendered we go through the whole rendered binary to trim the whitespaces?

Parse -> render -> trim whitespaces ? It's not super efficient but  at it seems more feasible and at least the feature gets implemented? We could then in the future try to optimise it. 

I haven't tried doing this as a separate step but I wonder if it would work 🤔

**Pull request closed without merging**
